## Matrices

In [3]:
import numpy as np

Add a function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [4]:
def copy_matrix(matrix):
    m = matrix
    return m

copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [25]:
def add_row(matrix):
    row = np.zeros(len(matrix[0]))
    extra_row = np.vstack([matrix,row])
    return extra_row

add_row([[3, 2, 5], [1, 4, 7]])

array([[3., 2., 5.],
       [1., 4., 7.],
       [0., 0., 0.]])

In [62]:
def add_column(matrix):
    column = np.zeros((len(matrix),1), dtype = int)
    extra_column = np.hstack([matrix,column])
    return extra_column

add_column([[3, 2], [5, 1], [4, 7]])


array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 0]])

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [64]:
def add_matrices(m1, m2):
    m1_matrix = np.array(m1)
    m2_matrix = np.array(m2)
    result = m1_matrix + m2_matrix
    return result

a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices(a,b)

array([[3, 4],
       [5, 6]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [66]:
def scalar_mult(s, m):
    m_matrix = np.array(m)
    multipl = m_matrix * s
    return multipl

b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
scalar_mult(10,b)

array([[30, 50, 70],
       [10, 10, 10],
       [ 0, 20,  0],
       [20, 20, 30]])

Write functions row_times_column and matrix_mult:

In [76]:
def row_times_column(m1, row, m2, column):
    m_1 = np.array(m1)
    m_2 = np.array(m2)
    r_c = np.dot(m_1[row] , m_2[:,column])
    return r_c

row_times_column ([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
    

19

In [77]:
def matrix_mult(m1, m2):
    multiply = np.dot(m1,m2)
    return multiply

matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])

    

array([[19, 22],
       [43, 50]])

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [71]:
def transpose(m):
    transp = np.transpose(m)
    return transp

m = [[3, 4, 6], [1, 5, 9]]
transpose(m)

array([[3, 1],
       [4, 5],
       [6, 9]])