In [1]:
import numpy as np

#### 72. How to swap two rows of an array? (★★★)

In [7]:
a = np.array([[5,7,8],[9,2,0]])
print(a)
b = np.flip(a, axis=0)
print(b)

[[5 7 8]
 [9 2 0]]
[[9 2 0]
 [5 7 8]]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [105]:
a = np.array([1,2,3,4])

a_sum = np.sum(a)
a_mean = a_sum/4
print(a_mean)

b_sum = np.sum(a[1:]) # remove first number and compute remaining three numbers averages
b_mean = b_sum/3
print(b_mean)

c_sum = np.sum(a[2:]) # remove first two numbers and compute remaining two numbers averages
c_mean = c_sum/2
print(c_mean)


2.5
3.0
3.5


In [130]:
# Trying to do the for loop here but failing

z = np.array([1,2,3,4])

def mva(nums):
    i = len(z)
    for i in nums:
        a_sum = np.sum(nums)
        a_mean = a_sum/i
        print(a_mean)
        i-=1

mva(z)


10.0
5.0
3.3333333333333335
2.5
