In [4]:
import numpy as np

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [3]:
a = np.random.rand(10,10)
print(a.max())
print(a.min())

0.9959881088127988
0.01869446048171719


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.zeros(16).reshape(4,4)
a[0] = 1
a[-1] = 1
a[:,0] = 1
a[:,-1] = 1
print(a)



[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
